### ISSUE TITLE
You need to enable the Ktorfit Gradle Plugin

### ISSUE THREAD

**Issue by ahmadmssm** [Foso/Ktorfit#107]
### Ktorfit version

1.0.0-beta17

### What happened and how can we reproduce this issue?

When trying to use the `create()` function to resolve an interface I get this error:
`You need to enable the Ktorfit Gradle Plugin`

But everything seems to be fine when I use the generated class (`createXYZ()` generated function).

### What did you expect to happen?

To get the same result that I get from the `createXYZ()` generated function.

**Comment by Foso** [comment]
Hi, when you want to use the create() function you need to add the Gradle plugin https://github.com/Foso/Ktorfit#gradle-plugins

**Comment by ahmadmssm** [comment]
Hi @Foso 

Thanks for your quick reply.
Already added it but still facing the same error.
Here are my plugins:
```
plugins {
    id ("com.android.application")
    id ("org.jetbrains.kotlin.android")
    id ("com.google.devtools.ksp") version "1.8.0-1.0.9"
    id ("org.jetbrains.kotlin.plugin.serialization") version "1.8.0"
    id("de.jensklingenberg.ktorfit") version "1.0.0"
}
```

**Comment by Foso** [comment]
That looks correct. Please take a look at the example projects if there something different

**Comment by ahmadmssm** [comment]
I made sure everything is set as per the example but still got the same error.

```
FATAL EXCEPTION: DefaultDispatcher-worker-1
                                                                                                    Process: com.ams.khdmaEmployeeId.uat, PID: 19810
                                                                                                    java.lang.IllegalArgumentException: You need to enable the Ktorfit Gradle Plugin
                                                                                                    	at de.jensklingenberg.ktorfit.Ktorfit.create(Ktorfit.kt:36)
                                                                                                    	at de.jensklingenberg.ktorfit.Ktorfit.create$default(Ktorfit.kt:34)
                                                                                                    	at com.ams.khdmaEmployeeId.data.httpClient.RestClientImpl.createAPI(RestClientImpl.kt:72)
                                                                                                    	at com.ams.khdmaEmployeeId.APIs.countriesAPIs(APIs.kt:12)
                                                                                                    	at com.ams.khdmaEmployeeId.scenes.fragments.QRCodeFragment$onViewCreated$1.invokeSuspend(QRCodeFragment.kt:26)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2036280, Dispatchers.Default]
```

**Comment by ahmadmssm** [comment]
I checked the implementation of the library, when calling the generated function, the debugger steps into this:
```
public fun Ktorfit.createCountriesAPIs(): CountriesAPIs = _CountriesAPIsImpl().also{
    it.setClient(KtorfitClient(this)) }
```
but with the `create` function, it never it is not invoked at all.

**Comment by Foso** [comment]
Is the create function inside a Coroutine? If so, please try it outside of one. I tried it inside of Coroutines, but maybe there is a bug

**Comment by ahmadmssm** [comment]
Yes, Inside a Coroutine

**Comment by ahmadmssm** [comment]
But how do I run a `suspend` function without a Coroutine, or do you mean to use `flow` as a return ?

**Comment by Foso** [comment]
just the create() outside of corutine, something like this:

val myApi = ktorfit.create<MyAp>()

GlobalScope.launch{
   myApi.request()
}

**Comment by ahmadmssm** [comment]
That's exactly what I'm doing, is there any other reason that might cause this error ?

**Comment by Foso** [comment]
When you do it like that i expect it to work. The Grade plugin triggers the compiler plugin. And that plugin will transform 
```kotlin
val api = jvmKtorfit.create<ExampleApi>()
```

 to:

```kotlin
val api = jvmKtorfit.create<ExampleApi>(_ExampleApiImpl())
```

The compiler plugin distinguish where in the code the create functions is used. https://github.com/Foso/Ktorfit/blob/master/compiler-plugin/src/main/java/de/jensklingenberg/ktorfit/ElementTransformer.kt

I thought i might missed some special case. 

Is the Gradle plugin applied to the module where you use the create function?

**Comment by ahmadmssm** [comment]
Except that it is not generating 😀 
Yes, it is applied to the module, the App is basically a demo app where I'm trying the library before applying it to a large code-base project, so yes, the App is a single module.

**Comment by Foso** [comment]
Okay, can you send me any code so I can reproduce the bug?

**Comment by ahmadmssm** [comment]
HYG
https://github.com/ahmadmssm/5dma-Employee-Id-Android

**Comment by Foso** [comment]
Thank you for providing the project, the issue here is the generics. The compiler plugin needs to know the type of the interface at compile time.
 
```
This will work: 
fun getApi(): CountriesAPIs = ktorfit.create()

This wont:
inline fun <reified T> getApi(): T = ktorfit.create()
```

This should have lead to a compile error, but the case wasn`t handled correct

**Comment by ahmadmssm** [comment]
Thank you.
The second worked but I think it is important to handle this case because generics are used heavily by many developers, and I usually prefer to hide implementations and only expose plain interfaces but with this case, I will be forced to expose the library implementation.

**Comment by Foso** [comment]
This should work on Android:

```
fun <API> getApi(cla : Class<API>): API {
    val qualifiedName = cla.canonicalName
    val packageName = qualifiedName?.substringBeforeLast(".")
    val className = cla.simpleName
    val myImplClass =  Class.forName("$packageName._${className}Impl").newInstance()

    return client.create(myImplClass as KtorfitService)
}
```

I would love to support generics, but the challenge that this should work as an Kotlin Multiplatform library. But with generics i need some kind of reflection and reflections can only be used on Android/Jvm and not iOS or JS. I want to avoid inconsistent behavior between the target platforms. I'm open to any ideas

**Comment by ahmadmssm** [comment]
Apologies for the late reply.
But this snippet is not super nice.
I know about the `Kotlin Multiplatform` constraints but why don't you provide a function specific to the environment, for example, you can expose the function we are talking about to Android only and another one for iOS, (I don't about Js 😅).
