### ISSUE TITLE
Getting error when using @Body annotation

### ISSUE THREAD

**Issue by gazanfarov** [Foso/Ktorfit#12]
I have a simple post request with http body:
```
@POST("users/update")
    fun updateUser(
        @Body user: UserUpdatingModel
    ): Call<UserModel>
```

Where UserUpdatingModel is:
```
@Serializable
data class UserUpdatingModel
```

Getting error:
```
2022-06-01 13:40:33.091 7620-7690/ua.blink E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6
    Process: ua.blink, PID: 7620
    java.lang.IllegalStateException: No request transformation found: UserUpdatingModel()
        at io.ktor.client.request.HttpRequestBuilder.build(HttpRequest.kt:118)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:130)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:126)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:91)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:125)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(HttpCallValidator.kt)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(HttpCallValidator.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
        at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invokeSuspend(HttpRequestLifecycle.kt:35)
        at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(HttpRequestLifecycle.kt)
        at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(HttpRequestLifecycle.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.client.HttpClient.execute$ktor_client_core(HttpClient.kt:184)
        at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:107)
        at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:46)
        at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:61)
        at ua.blink.shared.data.api._BlinkApiImpl$updateUser$$inlined$request$1.invokeSuspend(KtorfitClient.kt:256)
        at ua.blink.shared.data.api._BlinkApiImpl$updateUser$$inlined$request$1.invoke(KtorfitClient.kt)
        at ua.blink.shared.data.api._BlinkApiImpl$updateUser$$inlined$request$1.invoke(KtorfitClient.kt)
        at de.jensklingenberg.ktorfit.adapter.KtorfitCallResponseConverter$wrapResponse$1$onExecute$1$deferredResponse$1.invokeSuspend(KtorfitCallResponseWrapper.kt:27)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@28b84ca0, Dispatchers.Default]
```

**Comment by gazanfarov** [comment]
Fixed by adding @Headers annotation:
```
 @Headers(["Content-Type: application/json"])
    @PUT("users/update")
    fun updateUser(
        @Body user: UserUpdatingModel
    ): Call<UserModel>
```
