### ISSUE TITLE
[Bug]: Post request body serialization doesn't work

### ISSUE THREAD

**Issue by alapshin** [Foso/Ktorfit#202]
### Ktorfit version

1.0.0

### What happened and how can we reproduce this issue?

Sample repo
https://github.com/alapshin/multiplayground/tree/aa09943fb7cf180ac57a28e8c9db95874da9f0b6

See `LoginComponent` class. 
There are two implementation of `LoginService` interface. One generated by Ktorfit (enabled by default) and one written by hand using Ktor directly (commented out).

When sample app is launched and `Login` button is pressed login request is sent using `LoginService`.

When LoginService implementation generated by Ktorfit is used post request body serialization fails with following stacktrace
```
FATAL EXCEPTION: main
Process: com.example.multiplayground.android, PID: 3824
kotlinx.serialization.SerializationException: Serializer for class 'Any' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:92)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:207)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source:1)
	at io.ktor.serialization.kotlinx.SerializerLookupKt.serializerFromTypeInfo(SerializerLookup.kt:24)
	at io.ktor.serialization.kotlinx.KotlinxSerializationBase.serialize$ktor_serialization_kotlinx(KotlinxSerializationBase.kt:20)
	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.serializeNullable(KotlinxSerializationConverter.kt:54)
	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation.convertRequest$ktor_client_content_negotiation(ContentNegotiation.kt:180)
	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$1.invokeSuspend(ContentNegotiation.kt:251)
	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$1.invoke(Unknown Source:11)
	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.DebugPipelineContext.proceedLoop(DebugPipelineContext.kt:80)
	at io.ktor.util.pipeline.DebugPipelineContext.proceed(DebugPipelineContext.kt:57)
	at io.ktor.util.pipeline.DebugPipelineContext.proceedWith(DebugPipelineContext.kt:42)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:130)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(Unknown Source:13)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.DebugPipelineContext.proceedLoop(DebugPipelineContext.kt:80)
	at io.ktor.util.pipeline.DebugPipelineContext.proceed(DebugPipelineContext.kt:57)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invokeSuspend(HttpRequestLifecycle.kt:38)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(Unknown Source:11)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.DebugPipelineContext.proceedLoop(DebugPipelineContext.kt:80)
	at io.ktor.util.pipeline.DebugPipelineContext.proceed(DebugPipelineContext.kt:57)
	at io.ktor.util.pipeline.DebugPipelineContext.execute$ktor_utils(DebugPipelineContext.kt:63)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.client.HttpClient.execute$ktor_client_core(HttpClient.kt:191)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:108)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:47)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:62)
	at de.jensklingenberg.ktorfit.internal.KtorfitClient.suspendRequest(KtorfitClient.kt:367)
	at com.alapshin.multiplayground.login.data._LoginServiceImpl.login(_LoginServiceImpl.kt:22)
	at com.alapshin.multiplayground.login.data.LoginManagerImpl.login(LoginManagerImpl.kt:10)
	at com.alapshin.multiplayground.login.domain.LoginStoreFactory$ExecutorImpl$executeIntent$1$1.invokeSuspend(LoginStoreFactory.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)

```

But if I switch implementation to one wirtten by hand then request post body is serialized correctly.

HttpClient configuration is identical in both cases (see `NetworkComponent`). It seems that for some reasons Ktorfit doesn't set correct `bodyType` on `HttpRequest` but I can't figure why it happens.

### What did you expect to happen?

I expect implementation generated by Ktorfit serialize post body correctly.

**Comment by ahmadmssm** [comment]
I'm facing the same issue.

**Comment by ahmadmssm** [comment]
@Foso

**Comment by Foso** [comment]
Thank you for the bug report

**Comment by Foso** [comment]
I fixed it, i'm planning to release a new version on the weekend

**Comment by ahmadmssm** [comment]
Do you expect to have a new release soon ?

**Comment by Foso** [comment]
Have you tried it with 1.0.1 ?

**Comment by ahmadmssm** [comment]
Just tried with v1.0.1 and I can see that the issue is now fixed.
Thank you.

**Comment by terrakok** [comment]
ktorfit = "2.2.0"
Kotlin Multiplatform project.
```kotlin
@POST("api/v1/statuses")
    suspend fun createPost(
        @Body createPostDto: CreatePostDto
    ): Call<PostDto>

@Serializable
data class CreatePostDto(...)
```
 
I receive an error
```
java.lang.IllegalStateException: Fail to prepare request body for sending. 
The body type is: class com.[package].CreatePostDto (Kotlin reflection is not available), with Content-Type: null.

If you expect serialized body, please check that you have installed the corresponding plugin(like `ContentNegotiation`) and set `Content-Type` header.
```

The content negotiation plugin is installed:
```kotlin
HttpClient {
        install(ContentNegotiation) { json(json) }
}
```

**Comment by terrakok** [comment]
It works only if I convert the body object to JSON and add a content-type header
```kotlin
@Headers("Content-Type: application/json")
@POST("api/v1/statuses")
suspend fun createPost(
    @Body createPostDto: String
): Call<PostDto>
```

A similar problem is here: https://stackoverflow.com/questions/75672624/is-it-possible-to-use-a-serializable-data-class-as-post-request-body-in-ktorfit
