### ISSUE TITLE
[Bug]: Ksp Ktorfit plugin can't be applied to commonTest sourceSets

### ISSUE THREAD

**Issue by xiaobailong24** [Foso/Ktorfit#403]
### Ktorfit version

1.6.0

### What happened and how can we reproduce this issue?

Compile ERROR 👇👇
```
> Task :shared:compileTestKotlinJvm> Task :shared:compileTestKotlinJvm FAILED FAILED

e: java.lang.IllegalStateException: _TestApiImpl() not found, did you apply the Ksp Ktorfit plugin?e: java.lang.IllegalStateException: _TestApiImpl() not found, did you apply the Ksp Ktorfit plugin?

	at de.jensklingenberg.ktorfit.CreateFuncTransformer.visitExpression(CreateFuncTransformer.kt:67)	at de.jensklingenberg.ktorfit.CreateFuncTransformer.visitExpression(CreateFuncTransformer.kt:67)

	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclarationReference(IrElementTransformerVoid.kt:178)	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclarationReference(IrElementTransformerVoid.kt:178)

	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitMemberAccess(IrElementTransformerVoid.kt:208)	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitMemberAccess(IrElementTransformerVoid.kt:208)

	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFunctionAccess(IrElementTransformerVoid.kt:211)	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFunctionAccess(IrElementTransformerVoid.kt:211)

	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:214)	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:214)

	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:215)	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:215)

	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:24)	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:24)

	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:26)	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:26)

	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)

	at org.jetbrains.kotlin.ir.declarations.IrVariable.transformChildren(IrVariable.kt:45)	at org.jetbrains.kotlin.ir.declarations.IrVariable.transformChildren(IrVariable.kt:45)
```

Demo:
https://github.com/xiaobailong24/Ktorfit/blob/master/example/MultiplatformExample/shared/src/commonTest/kotlin/com/example/ktorfittest/KtorfitTest.kt#L9

### What did you expect to happen?

Ksp Ktorfit plugin can be applied to commonTest sourceSets

**Comment by xiaobailong24** [comment]
Fix: https://github.com/Foso/Ktorfit/pull/404
