### ISSUE TITLE
[Bug]:  java.lang.IllegalArgumentException: You need to enable the Ktorfit Gradle Plugin

### ISSUE THREAD

**Issue by ferenczAndras** [Foso/Ktorfit#405]
### Ktorfit version

1.6.0

### What happened and how can we reproduce this issue?

```
FATAL EXCEPTION: main
                                                                                                    Process: com.app.app, PID: 12145
                                                                                                    java.lang.IllegalArgumentException: You need to enable the Ktorfit Gradle Plugin
                                                                                                    	at de.jensklingenberg.ktorfit.Ktorfit.create(Ktorfit.kt:98)
                                                                                                    	at de.jensklingenberg.ktorfit.Ktorfit.create$default(Ktorfit.kt:96)
                                                                                                    	at com.app.core.api.ApiClientProvider$api$2.invoke(ApiClientProvider.kt:29)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.app.core.api.ApiClientProvider.getApi(ApiClientProvider.kt:29)
                                                                                                    	at com.app.core.api.BaseRepository$API$2.invoke(BaseRepository.kt:7)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.app.core.api.BaseRepository.getAPI(BaseRepository.kt:6)
                                                                                                    	at com.app.feature.user.UserRepository.login(UserRepository.kt:8)
                                                                                                    	at com.app.feature.login.LoginViewModel$onEvent$3.invokeSuspend(LoginViewModel.kt:42)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at com.app.feature.login.LoginViewModel.onEvent(LoginViewModel.kt:41)
                                                                                                    	at com.app.presentation.login.LoginScreenKt$LoginScreen$2$3$1.invoke(LoginScreen.kt:98)
                                                                                                    	at com.app.presentation.login.LoginScreenKt$LoginScreen$2$3$1.invoke(LoginScreen.kt:96)
                                                                                                    	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:895)
                                                                                                    	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:889)
                                                                                                    	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:665)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:544)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:566)
                                                                                                    	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:855)
                                                                                                    	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:703)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
                                                                                                    	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
                                                                                                    	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
2023-09-04 16:02:34.410 12145-12145 AndroidRuntime          com.app.h2oTeam                E  	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:96)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1446)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1398)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1338)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1905)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4263)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:15262)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6654)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6454)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5910)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6098)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6155)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8996)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8947)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8916)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9119)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1bb87ad, Dispatchers.Main.immediate]
```

### What did you expect to happen?

Can you help me figure out why? 

`class ApiClientProvider<T> constructor(private val baseUrl: String) {

    private val ktorfit by lazy {
        ktorfit {
            baseUrl(baseUrl)
            httpClient(HttpClient {
                install(ContentNegotiation) {
                    json(Json { isLenient = true; ignoreUnknownKeys = true })
                }
            })
            converterFactories(
                FlowConverterFactory(),
                CallConverterFactory(),
            )
        }
    }

    val api by lazy { ktorfit.create<T>() }

}`

**Comment by xiaobailong24** [comment]
`ktorfit.create<T>()` is NOT supported, you should specify KClass instead of generic T.

**Comment by Foso** [comment]
Hey @ferenczAndras , @xiaobailong24 is right, i also think that the generic is the problem here

**Comment by ferenczAndras** [comment]
Yes, thank you @Foso  and @xiaobailong24. I just hope one day it will be. Anyway, great library.
