### ISSUE TITLE
Ktorfit inside Koin module does not compile after version 1.9.1

### ISSUE THREAD

**Issue by ageorgousakis** [Foso/Ktorfit#505]
### Ktorfit version

1.11.0

### What happened and how can we reproduce this issue?

Using any Ktorfit version after 1.9.1 with Koin gives compilations errors like:

```
e: file:///.../ktor-koin-ktorfit-test/src/main/kotlin/example/ClientsModule.kt:33:9 Inherited platform declarations clash: The following declarations have the same JVM signature (invoke(Ljava/lang/Object;)Ljava/lang/Object;):
    fun invoke(p1: Any?): Any? defined in example.clientsModule.`<no name provided>`.invoke.`<no name provided>`.invoke.`<no name provided>`
    fun invoke(p1: Any?): Any? defined in example.clientsModule.`<no name provided>`.invoke.`<no name provided>`.invoke.`<no name provided>`
```

I created a sample repo [ktor-koin-ktorfit-test](https://github.com/ageorgousakis/ktor-koin-ktorfit-test)  to test it. Change `ktorfit` version to 1.11.0 at `gradle/libs.versions.toml` and try to rebuild the project.

### What did you expect to happen?

Project to be build correctly

### Is there anything else we need to know about?

Also in other more complicated project where I try to upgrade ktorfit to the latest version using K2 compiler I receive more strange errors like:

```
org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
File being compiled: /.../services/form/form-service/src/main/kotlin/net/xxxx/xxx/config/ClientsModule.kt
The root cause org.jetbrains.kotlin.backend.common.CompilationException was thrown at: org.jetbrains.kotlin.ir.symbols.impl.IrBindableSymbolBase.getOwner(IrPrivateSymbolBase.kt)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:253)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException$default(CodegenUtil.kt:237)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invokeSequential(performByIrFile.kt:65)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(performByIrFile.kt:52)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(performByIrFile.kt:38)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.phaseBody(CompilerPhase.kt:147)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedCompilerPhase.invoke(CompilerPhase.kt:94)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:29)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:16)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.phaseBody(CompilerPhase.kt:147)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedCompilerPhase.invoke(CompilerPhase.kt:94)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:43)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.invokeLowerings(JvmIrCodegenFactory.kt:348)
	at org.jetbrains.kotlin.codegen.CodegenFactory.generateModule(CodegenFactory.kt:44)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModuleInFrontendIRMode(JvmIrCodegenFactory.kt:379)
	at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.CompilerPipelineKt.generateCodeFromIr(compilerPipeline.kt:245)
	at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.CompilerPipelineKt.compileModulesUsingFrontendIrAndLightTree(compilerPipeline.kt:151)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:146)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:463)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:62)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:477)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:400)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:281)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:125)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:657)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:105)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1624)
	at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jetbrains.kotlin.backend.common.CompilationException: Back-end: Please report this problem https://kotl.in/issue
/.../form/form-service/src/main/kotlin/net/xxxx/xxx/config/ClientsModule.kt:1:1
Problem with `class ClientsModuleKt {
  fun clientsModule(config: Config): Module {
    return module(, moduleDeclaration = { // BLOCK
      package class <no name provided> : Lambda, Function1<Module, Unit> {
        constructor() /* primary */ {
          super/*Lambda*/(arity = 1)
          /* <init>() */

        }

        override fun invoke($this$module: Module) {
          $this$module.single<HttpClient>(qualifier = named(name = "SystemHttpClient"), definition = { // BLOCK
            package class <no name provided> : Lambda, Function2<Scope, ParametersHolder, HttpClient> {
              package constructor($config: Config) /* primary */ {
                <this>.#$config = $config
                super/*Lambda*/(arity = 2)
                /* <init>() */

              }

              override fun invoke($this$single: Scope, it: ParametersHolder): HttpClient {
                return systemHttpClient(clientCredentialsConfig = <this>.#$config.<get-clientCredentials>())
              }

              package /* final field */ val $config: Config
            }

            <no name provided>()
          }) /*~> Unit */
          $this$module.single<HttpClient>(qualifier = named(name = "UserHttpClient"), definition = { // BLOCK
            package class <no name provided> : Lambda, Function2<Scope, ParametersHolder, HttpClient> {
              package constructor() /* primary */ {
                super/*Lambda*/(arity = 2)
                /* <init>() */

              }

              override fun invoke($this$single: Scope, it: ParametersHolder): HttpClient {
                return userHttpClient()
              }

            }

            <no name provided>()
          }) /*~> Unit */
          val clientsConfig: ClientsConfig = config.<get-clients>()
          $this$module.single<OrganizationServiceClient>(, definition = { // BLOCK
            package class <no name provided> : Lambda, Function2<Scope, ParametersHolder, OrganizationServiceClient> {
              package constructor($clientsConfig: ClientsConfig) /* primary */ {
                super/*Lambda*/(arity = 2)
                /* <init>() */

              }

              override fun invoke($this$single: Scope, it: ParametersHolder): OrganizationServiceClient {
                return ktorfit(builder = { // BLOCK
                  package class <no name provided> : Lambda, Function1<Builder, Unit> {
                    package constructor($clientsConfig: ClientsConfig, $this_single: Scope) /* primary */ {
                      <this>.#$clientsConfig = $clientsConfig
                      <this>.#$this_single = $this_single
                      super/*Lambda*/(arity = 1)
                      /* <init>() */

                    }

                    override fun invoke($this$ktorfit: Builder) {
                      $this$ktorfit.baseUrl(url = <this>.#$clientsConfig.<get-identityServiceUri>().plus(other = "/")) /*~> Unit */
                      $this$ktorfit.httpClient(client = <this>.#$this_single.get<HttpClient>(qualifier = named(name = "SystemHttpClient")) as HttpClient) /*~> Unit */
                      $this$ktorfit.converterFactories(converters = { // BLOCK
                        val tmp0: Array<out Factory> = arrayOfNulls<Factory>(size = 1)
                        tmp0.set(index = 0, value = DefaultResponseConverterFactory())
                        tmp0
                      }) /*~> Unit */
                    }

                    package /* final field */ val $clientsConfig: ClientsConfig
                    package /* final field */ val $this_single: Scope
                  }

                  <no name provided>($clientsConfig = <this>.#/* ERROR: unbound symbol null */, $this_single = $this$single)
                }).create<OrganizationServiceClient>(data = _OrganizationServiceClientImpl(_ktorfit = ktorfit(builder = { // BLOCK
                  package class <no name provided> : Lambda, Function1<Builder, Unit> {
                    package constructor($clientsConfig: ClientsConfig, $this_single: Scope) /* primary */ {
                      <this>.#$clientsConfig = $clientsConfig
                      <this>.#$this_single = $this_single
                      super/*Lambda*/(arity = 1)
                      /* <init>() */

                    }

                    override fun invoke($this$ktorfit: Builder) {
                      $this$ktorfit.baseUrl(url = <this>.#$clientsConfig.<get-identityServiceUri>().plus(other = "/")) /*~> Unit */
                      $this$ktorfit.httpClient(client = <this>.#$this_single.get<HttpClient>(qualifier = named(name = "SystemHttpClient")) as HttpClient) /*~> Unit */
                      $this$ktorfit.converterFactories(converters = { // BLOCK
                        val tmp0: Array<out Factory> = arrayOfNulls<Factory>(size = 1)
                        tmp0.set(index = 0, value = DefaultResponseConverterFactory())
                        tmp0
                      }) /*~> Unit */
                    }

                    package /* final field */ val $clientsConfig: ClientsConfig
                    package /* final field */ val $this_single: Scope
                  }

                  <no name provided>($clientsConfig = <this>.#/* ERROR: unbound symbol null */, $this_single = $this$single)
                })))
              }

            }

            <no name provided>()
          }) /*~> Unit */
          $this$module.single<ProjectServiceClient>(, definition = { // BLOCK
            package class <no name provided> : Lambda, Function2<Scope, ParametersHolder, ProjectServiceClient> {
              constructor() /* primary */ {
                super/*Lambda*/(arity = 2)
                /* <init>() */

              }

              override fun invoke($this$single: Scope, it: ParametersHolder): ProjectServiceClient {
                return ktorfit(builder = { // BLOCK
                  package class <no name provided> : Lambda, Function1<Builder, Unit> {
                    constructor() /* primary */ {
                      super/*Lambda*/(arity = 1)
                      /* <init>() */

                    }

                    override fun invoke($this$ktorfit: Builder) {
                      $this$ktorfit.baseUrl(url = clientsConfig.<get-projectServiceUri>().plus(other = "/")) /*~> Unit */
                      $this$ktorfit.httpClient(client = $this$single.get<HttpClient>(qualifier = named(name = "UserHttpClient")) as HttpClient) /*~> Unit */
                      $this$ktorfit.converterFactories(converters = { // BLOCK
                        val tmp0: Array<out Factory> = arrayOfNulls<Factory>(size = 1)
                        tmp0.set(index = 0, value = DefaultResponseConverterFactory())
                        tmp0
                      }) /*~> Unit */
                    }

                  }

                  <no name provided>()
                }).create<ProjectServiceClient>(data = _ProjectServiceClientImpl(_ktorfit = ktorfit(builder = { // BLOCK
                  package class <no name provided> : Lambda, Function1<Builder, Unit> {
                    constructor() /* primary */ {
                      super/*Lambda*/(arity = 1)
                      /* <init>() */

                    }

                    override fun invoke($this$ktorfit: Builder) {
                      $this$ktorfit.baseUrl(url = clientsConfig.<get-projectServiceUri>().plus(other = "/")) /*~> Unit */
                      $this$ktorfit.httpClient(client = $this$single.get<HttpClient>(qualifier = named(name = "UserHttpClient")) as HttpClient) /*~> Unit */
                      $this$ktorfit.converterFactories(converters = { // BLOCK
                        val tmp0: Array<out Factory> = arrayOfNulls<Factory>(size = 1)
                        tmp0.set(index = 0, value = DefaultResponseConverterFactory())
                        tmp0
                      }) /*~> Unit */
                    }

                  }

                  <no name provided>()
                })))
              }

            }

            <no name provided>()
          }) /*~> Unit */
          $this$module.single<StateFlowServiceClient>(, definition = { // BLOCK
            package class <no name provided> : Lambda, Function2<Scope, ParametersHolder, StateFlowServiceClient> {
              constructor() /* primary */ {
                super/*Lambda*/(arity = 2)
                /* <init>() */

              }

              override fun invoke($this$single: Scope, it: ParametersHolder): StateFlowServiceClient {
                return ktorfit(builder = { // BLOCK
                  package class <no name provided> : Lambda, Function1<Builder, Unit> {
                    constructor() /* primary */ {
                      super/*Lambda*/(arity = 1)
                      /* <init>() */

                    }

                    override fun invoke($this$ktorfit: Builder) {
                      $this$ktorfit.baseUrl(url = clientsConfig.<get-stateServiceUri>().plus(other = "/")) /*~> Unit */
                      $this$ktorfit.httpClient(client = $this$single.get<HttpClient>(qualifier = named(name = "UserHttpClient")) as HttpClient) /*~> Unit */
                      $this$ktorfit.converterFactories(converters = { // BLOCK
                        val tmp0: Array<out Factory> = arrayOfNulls<Factory>(size = 1)
                        tmp0.set(index = 0, value = DefaultResponseConverterFactory())
                        tmp0
                      }) /*~> Unit */
                    }

                  }

                  <no name provided>()
                }).create<StateFlowServiceClient>(data = _StateFlowServiceClientImpl(_ktorfit = ktorfit(builder = { // BLOCK
                  package class <no name provided> : Lambda, Function1<Builder, Unit> {
                    constructor() /* primary */ {
                      super/*Lambda*/(arity = 1)
                      /* <init>() */

                    }

                    override fun invoke($this$ktorfit: Builder) {
                      $this$ktorfit.baseUrl(url = clientsConfig.<get-stateServiceUri>().plus(other = "/")) /*~> Unit */
                      $this$ktorfit.httpClient(client = $this$single.get<HttpClient>(qualifier = named(name = "UserHttpClient")) as HttpClient) /*~> Unit */
                      $this$ktorfit.converterFactories(converters = { // BLOCK
                        val tmp0: Array<out Factory> = arrayOfNulls<Factory>(size = 1)
                        tmp0.set(index = 0, value = DefaultResponseConverterFactory())
                        tmp0
                      }) /*~> Unit */
                    }

                  }

                  <no name provided>()
                })))
              }

            }

            <no name provided>()
          }) /*~> Unit */
        }

      }

      <no name provided>()
    })
  }

}

`
Details: Internal error in body lowering: java.lang.IllegalStateException: IrFieldSymbolImpl is unbound. Signature: null
	at org.jetbrains.kotlin.ir.symbols.impl.IrBindableSymbolBase.getOwner(IrPrivateSymbolBase.kt)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer$FunctionBodiesRewriter.visitDeclarationReference(LocalDeclarationsLowering.kt:517)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFieldAccess(IrElementTransformerVoid.kt:199)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitGetField(IrElementTransformerVoid.kt:202)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitGetField(IrElementTransformerVoid.kt:203)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitGetField(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrGetField.accept(IrGetField.kt:21)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:45)
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.transformChildren(IrMemberAccessExpression.kt:50)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer$FunctionBodiesRewriter.visitConstructorCall(LocalDeclarationsLowering.kt:408)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitConstructorCall(IrElementTransformerVoid.kt:218)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitConstructorCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrConstructorCall.accept(IrConstructorCall.kt:28)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.expressions.IrContainerExpression.transformChildren(IrContainerExpression.kt:31)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:131)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitContainerExpression(IrElementTransformerVoid.kt:166)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:169)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:170)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:20)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:45)
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.transformChildren(IrMemberAccessExpression.kt:50)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer$FunctionBodiesRewriter.visitCall(LocalDeclarationsLowering.kt:399)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:215)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:26)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:45)
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.transformChildren(IrMemberAccessExpression.kt:50)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer$FunctionBodiesRewriter.visitConstructorCall(LocalDeclarationsLowering.kt:408)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitConstructorCall(IrElementTransformerVoid.kt:218)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitConstructorCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrConstructorCall.accept(IrConstructorCall.kt:28)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:45)
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.transformChildren(IrMemberAccessExpression.kt:50)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer$FunctionBodiesRewriter.visitCall(LocalDeclarationsLowering.kt:399)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:215)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:26)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrReturn.transformChildren(IrReturn.kt:33)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer$FunctionBodiesRewriter.visitReturn(LocalDeclarationsLowering.kt:504)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitReturn(IrElementTransformerVoid.kt:309)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitReturn(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrReturn.accept(IrReturn.kt:26)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.transformChildren(IrBlockBody.kt:32)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBody(IrElementTransformerVoid.kt:108)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:117)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:118)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:25)
	at org.jetbrains.kotlin.ir.expressions.IrBody.transform(IrBody.kt:22)
	at org.jetbrains.kotlin.ir.declarations.IrFunction.transformChildren(IrFunction.kt:62)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer$FunctionBodiesRewriter.visitMember(LocalDeclarationsLowering.kt:348)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer$FunctionBodiesRewriter.visitFunction(LocalDeclarationsLowering.kt:342)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:72)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:73)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:37)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:24)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.declarations.IrClass.transformChildren(IrClass.kt:83)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer.rewriteClassMembers(LocalDeclarationsLowering.kt:538)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer.rewriteDeclarations(LocalDeclarationsLowering.kt:597)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering$LocalDeclarationsTransformer.lowerLocalDeclarations(LocalDeclarationsLowering.kt:298)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering.lower(LocalDeclarationsLowering.kt:96)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor$visitBody$1.invoke(Lower.kt:193)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor$visitBody$1.invoke(Lower.kt:192)
	at org.jetbrains.kotlin.ir.declarations.StageController.restrictTo(PersistentApi.kt:11)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBody(Lower.kt:192)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBody(Lower.kt:171)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitBlockBody(IrElementVisitor.kt:163)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBlockBody(Lower.kt:171)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBlockBody(Lower.kt:171)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:25)
	at org.jetbrains.kotlin.ir.declarations.IrFunction.acceptChildren(IrFunction.kt:54)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitDeclaration(Lower.kt:180)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitDeclaration(Lower.kt:171)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitFunction(IrElementVisitor.kt:112)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitFunction(Lower.kt:171)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitFunction(Lower.kt:171)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitSimpleFunction(IrElementVisitor.kt:139)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitSimpleFunction(Lower.kt:171)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitSimpleFunction(Lower.kt:171)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:37)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitClass(Lower.kt:186)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitClass(Lower.kt:171)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:73)
	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix(Lower.kt:150)
	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix$default(Lower.kt:143)
	at org.jetbrains.kotlin.backend.common.lower.LocalDeclarationsLowering.lower(LocalDeclarationsLowering.kt:86)
	at org.jetbrains.kotlin.backend.common.phaser.FileLoweringPhaseAdapter.invoke(PhaseBuilders.kt:120)
	at org.jetbrains.kotlin.backend.common.phaser.FileLoweringPhaseAdapter.invoke(PhaseBuilders.kt:116)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.phaseBody(CompilerPhase.kt:147)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedCompilerPhase.invoke(CompilerPhase.kt:94)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invokeSequential(performByIrFile.kt:62)
	... 44 more
Caused by: java.lang.IllegalStateException: IrFieldSymbolImpl is unbound. Signature: null
	... 160 more
```

**Comment by Foso** [comment]
Thank you for your bug report!

**Comment by ageorgousakis** [comment]
After further investigation I found that it is not related to Koin. Also this pattern fails without using Koin 

```kotlin
fun httpClient() =
    HttpClient {
        install(ContentNegotiation) {
            json(Json {
                ignoreUnknownKeys = true
            })
        }
        defaultRequest {
            headers {
                HttpHeaders.Accept to "application/json"
                HttpHeaders.ContentType to "application/json"
            }
        }
    }

fun startWarsApi() =
    ktorfit {
        baseUrl(StarWarsClient.baseUrl)
        httpClient(httpClient())
    }.create<StarWarsClient>()

fun Application.configure() {
    install(ContentNegotiation) {
        json(Json {
            ignoreUnknownKeys = true
        })
    }
    routing {
        val client = startWarsApi()
        
        get("/") {
            call.respond(mapOf("status" to "OK"))
        }

        get("/{id}") {
            val id = call.parameters.getOrFail("id")
            call.respond(client.getPersonById(id))
        }
    }
}
```

**Comment by Foso** [comment]
Hi, i found the reason for that issue. It currently only works when you when call the create function on a variable. So as a workaround till i know how to fix the isuse, you can do it like this: 
`single {
        val ktorfit = ktorfit {
            baseUrl(TestClient.baseUrl)
            httpClient(get() as HttpClient)
        }
        ktorfit.create<TestClient>()
    }`

**Comment by Foso** [comment]
Hi, with 1.11.1 it should work again

**Comment by ageorgousakis** [comment]
Yes, it is working
