### ISSUE TITLE
FlowConverterFacotry: java.util.NoSuchElementException: List is empty.

### ISSUE THREAD

**Issue by ahmadmssm** [Foso/Ktorfit#511]
### Ktorfit version

1.11.1

### What happened and how can we reproduce this issue?

I didn't find the `FlowConverterFactory` in the last version as I previously reported, so I copied it from the Repo but when trying to parse any response it falls at this line
` val response = getResponse()`
with this error
`java.util.NoSuchElementException: List is empty.`

### What did you expect to happen?

The parsing to success as in the previous versions.

**Comment by ahmadmssm** [comment]
I rolled back to a previous build and both bugs were not reproducible.

**Comment by ahmadmssm** [comment]
The issue is here 
```
  if (requestType.typeInfo.type == HttpResponse::class)
                            emit(getResponse())
```
if I add more than one response converter, it will jump automatically when I call `getResponse()` to the other response converter, if there is only one converter, then it will work as expected.

**Comment by ahmadmssm** [comment]
@Foso I'm facing this issue in production.

**Comment by niyajali** [comment]
Hi, I'm getting the same error on the `release` build whereas on debug build it's works fine.


ktorVersion = "3.0.0"
ktorfit = "2.1.0"
ktorfitKsp = "2.1.0-1.0.26"

```
Caused by: java.util.NoSuchElementException: List is empty.                                                                                 
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:221)                                                          
	at org.mifospay.core.network.utils.FlowConverterFactory$responseConverter$1.convert(FlowConverterFactory.kt:32)                         
	at org.mifospay.core.network.utils.FlowConverterFactory$responseConverter$1.convert(FlowConverterFactory.kt:30)                         
	at de.jensklingenberg.ktorfit.internal.KtorfitConverterHelper.request(KtorfitConverterHelper.kt:33)                                     
	at org.mifospay.core.network.services._ClientServiceImpl.getAccounts(_ClientServiceImpl.kt:148)                                         
	at org.mifospay.core.data.repositoryImp.SelfServiceRepositoryImpl.getActiveAccountsWithTransactions(SelfServiceRepositoryImpl.kt:139)   
	at org.mifospay.feature.home.HomeViewModel.<init>(HomeViewModel.kt:47)                                                                  
	at org.mifospay.feature.home.di.HomeModuleKt$HomeModule$lambda$0$$inlined$viewModelOf$default$1.invoke(ViewModelOf.kt:17)               
	at org.mifospay.feature.home.di.HomeModuleKt$HomeModule$lambda$0$$inlined$viewModelOf$default$1.invoke(ViewModelOf.kt:59) (Ask Gemini)  
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)                                                                 
```

**Comment by ahmadmssm** [comment]
@niyajali 
Try using the following combination together 
ktorVersion = "3.0.0"
ktorfit = "2.1.0"
ktorfitKsp = "2.0.21-1.0.25"

**Comment by Foso** [comment]
@niyajali Could be an issue with R8. What does your ConverterFactory look like?

**Comment by niyajali** [comment]
I'm using Ktorfit FlowConverterFactory

**Comment by Foso** [comment]
@niyajali So you are using exactly the same code as in here in your code? https://github.com/Foso/Ktorfit/blob/master/ktorfit-converters/flow/src/commonMain/kotlin/de/jensklingenberg/ktorfit/converter/FlowConverterFactory.kt 

I'm asking because based on the package name "org.mifospay.core.network.utils.FlowConverterFactory" you are using your own class and i have other way of knowing what the code in there looks like

**Comment by niyajali** [comment]
@Foso Yes I've copied exact same code, and also tried with `ktorfit-flow-converter` library and getting the same error on release build

**Comment by niyajali** [comment]
```
package org.mifospay.core.network.utils

import de.jensklingenberg.ktorfit.Ktorfit
import de.jensklingenberg.ktorfit.converter.Converter
import de.jensklingenberg.ktorfit.converter.KtorfitResult
import de.jensklingenberg.ktorfit.converter.TypeData
import io.ktor.client.call.body
import io.ktor.client.statement.HttpResponse
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

/**
 * Factory that enables the use of Flow<T> as return type
 */
public class FlowConverterFactory : Converter.Factory {
    override fun responseConverter(
        typeData: TypeData,
        ktorfit: Ktorfit,
    ): Converter.ResponseConverter<HttpResponse, *>? {
        if (typeData.typeInfo.type == Flow::class) {
            return object : Converter.ResponseConverter<HttpResponse, Flow<Any?>> {
                override fun convert(getResponse: suspend () -> HttpResponse): Flow<Any?> {
// Getting error on below line, somehow typeArgs is empty after applying progurd, so when we calling first() resulting NoSuchElementException
                    val requestType = typeData.typeArgs.first() 
                    return flow {
                        val response = getResponse()
                        if (requestType.typeInfo.type == HttpResponse::class) {
                            emit(response)
                        } else {
                            val convertedBody =
                                ktorfit.nextSuspendResponseConverter(
                                    this@FlowConverterFactory,
                                    typeData.typeArgs.first(),
                                )?.convert(KtorfitResult.Success(response))
                                    ?: response.body(typeData.typeArgs.first().typeInfo)
                            emit(convertedBody)
                        }
                    }
                }
            }
        }
        return null
    }
}
```

**Comment by niyajali** [comment]
@Foso Hi, is there any workaround or fix for this issue, I'm getting the above error even after I've excluded the `ktor` and `ktorfit` libraries in Proguard.

```
-keep class io.ktor.** { *; }
-keep class kotlinx.serialization.** { *; }
-keep class io.ktor.client.network.sockets.** { *; }
-keep class io.ktor.client.plugins.* { *; }
-keep class io.ktor.util.* { *; }
-keep class io.ktor.utils.io.* { *; }
-keep class java.lang.management.* { *; }
-dontwarn io.ktor.client.network.sockets.SocketTimeoutException
-dontwarn java.lang.management.RuntimeMXBean

# JSR 305 annotations are for embedding nullability information.
-dontwarn javax.annotation.**

# A resource is loaded with a relative path so the package of this class must be preserved.
-keeppackagenames okhttp3.internal.publicsuffix.*
-adaptresourcefilenames okhttp3/internal/publicsuffix/PublicSuffixDatabase.gz

# Animal Sniffer compileOnly dependency to ensure APIs are compatible with older versions of Java.
-dontwarn org.codehaus.mojo.animal_sniffer.*

# OkHttp platform used only on JVM and when Conscrypt and other security providers are available.
-dontwarn okhttp3.internal.platform.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**

-keep class org.mifospay.core.network.services.* { *;}
-keep class de.jensklingenberg.ktorfit.converter.** { *; }
-keep class de.jensklingenberg.ktorfit.** { *; }
-keeppackagenames de.jensklingenberg.ktorfit.*

```

```

Caused by: java.util.NoSuchElementException: List is empty.                                        
	at kotlin.collections.CollectionsKt___CollectionsKt.first(SourceFile:14)                       
	at a8.c.convert(Unknown Source:11)                                                             
	at de.jensklingenberg.ktorfit.internal.KtorfitConverterHelper.request(Unknown Source:24)       
	at org.mifospay.core.network.services._ClientServiceImpl.getAccounts(Unknown Source:49)        
	at D8.M.<init>(Unknown Source:75)                                                              
	at A8.b.invoke(Unknown Source:1304)                                                            
	at O6.b.a(Unknown Source:52)                                                                   
	... 175 more                                                                                   
	
```

**Comment by Foso** [comment]
I can not reproduce it, can someone give me a project where the error occurs?

**Comment by kpatel2000** [comment]
Hi @Foso , getting InstanceCreationException.
```Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Factory: 'org.mifospay.feature.home.HomeViewModel']'```

**Repo to reproduce:** [Repo](https://github.com/kpatel2000/mobile-wallet)
**Branch name:** MW-189_ktorfit_anr

Looking forward to any insights or suggestions to resolve this.

**Comment by Foso** [comment]
Hi @kpatel2000 i looked into your Repo. Sorry if i'm mistaken, but i don't see how it is related to this issue? I don't see any use of Ktorfit in your HomeViewModel. Your error message looks like a problem with Koin. Are you getting a NoSuchElementExeption in your FlowConverterFactoy?

**Comment by kpatel2000** [comment]
You are correct @Foso , my bad. Actually the issue raised by niyajali can be replicated through this repo. I will figure out this koin issue and get back to you if NoSuchElementException is still there.
