### ISSUE TITLE
How to handle http errors with ktrofit

### ISSUE THREAD

**Issue by hatched-MaciejPrzybylski** [Foso/Ktorfit#523]
I've tried to look everywhere but I'm not able to solve this

I have following configuration

```
private val httpClient = HttpClient {
        HttpResponseValidator {
            handleResponseExceptionWithRequest{ exception, request ->
                val clientException = exception as? ClientRequestException ?: return@handleResponseExceptionWithRequest
                val exceptionResponse = clientException.response
                throw ServerError(exceptionResponse.status, exceptionResponse.bodyAsText())
            }
        }
        install(ContentNegotiation) {
            json(Json { isLenient = true; ignoreUnknownKeys = true })
        }
        install(Logging) {
            logger = object : Logger {
                override fun log(message: String) {
                    println(message)
                }
            }
            level = LogLevel.ALL
            sanitizeHeader { header -> header == HttpHeaders.Authorization }
        }
        install(DefaultRequest) {
            if (!headers.contains("Authorization")) {
                auth?.access_token?.let {
                    header("Authorization", "Bearer ${it}")
                }

            }
        }
    }

private val ktorfit = ktorfit {
        baseUrl("https://myserver.com/")
        httpClient(httpClient)
    }

```

but when there is http error like 401 I'm allways getting 
`io.ktor.client.call.NoTransformationFoundException: Expected response body of the type`

how to configure ktrofit to be able to catch http errors

```
  FROM: https://myserver.com
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  COMMON HEADERS
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> cache-control: no-cache, no-store, max-age=0, must-revalidate; no-cache, no-store, max-age=0, must-revalidate
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> content-length: 0
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> cross-origin-embedder-policy: require-corp
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> cross-origin-opener-policy: same-origin-allow-popups
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> cross-origin-resource-policy: cross-origin
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> date: Sun, 03 Mar 2024 11:42:23 GMT
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> expect-ct: max-age=86400, enforce
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> expires: 0
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> pragma: no-cache; no-cache
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> server: openresty
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> strict-transport-security: max-age=31536000 ; includeSubDomains; max-age=31536000; includeSubDomains
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> vary: Origin; Access-Control-Request-Method; Access-Control-Request-Headers
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> www-authenticate: Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: Jwt expired at 2024-03-03T08:23:26Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> x-content-security-policy: default-src 'self'
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> x-content-type-options: nosniff; nosniff
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> x-frame-options: DENY; DENY
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> x-permitted-cross-domain-policies: none
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> x-webkit-csp: default-src 'self'
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  -> x-xss-protection: 0; 1; mode=block
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  BODY Content-Type: null
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  BODY START
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  
2024-03-03 12:42:23.378 15345-18873 System.out              com.hatak.autoauction                I  BODY END
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  io.ktor.client.call.NoTransformationFoundException: Expected response body of the type 'class com.hatak.autoauction.webservice.model.auth.UserBasic' but was 'class io.ktor.utils.io.ByteBufferChannel'
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  In response from `https://elicytacje.komornik.pl/services/auctioner-back/rest/user/basic`
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  Response status `401 `
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  Response header `ContentType: null` 
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  Request header `Accept: application/json`
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  You can read how to resolve NoTransformationFoundException at FAQ: 
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  https://ktor.io/docs/faq.html#no-transformation-found-exception
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  	at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:94)
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  	at io.ktor.client.call.HttpClientCall.body(HttpClientCall.kt:115)
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  	at de.jensklingenberg.ktorfit.converter.builtin.DefaultSuspendResponseConverterFactory$DefaultSuspendResponseConverter.convert(DefaultSuspendResponseConverterFactory.kt:28)
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  	at de.jensklingenberg.ktorfit.internal.KtorfitConverterHelper.suspendRequest(KtorfitConverterHelper.kt:112)
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  	at de.jensklingenberg.ktorfit.internal.KtorfitConverterHelper$suspendRequest$1.invokeSuspend(Unknown Source:15)
2024-03-03 12:42:23.397 15345-18907 System.err              com.hatak.autoauction                W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-03-03 12:42:23.398 15345-18907 System.err              com.hatak.autoauction                W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
2024-03-03 12:42:23.398 15345-18907 System.err              com.hatak.autoauction                W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2024-03-03 12:42:23.398 15345-18907 System.err              com.hatak.autoauction                W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2024-03-03 12:42:23.398 15345-18907 System.err              com.hatak.autoauction                W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2024-03-03 12:42:23.398 15345-18907 System.err              com.hatak.autoauction                W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by hatched-MaciejPrzybylski** [comment]
expectSuccess = true solved my problem
