### ISSUE TITLE
Can't handle io.ktor.serialization.JsonConvertException

### ISSUE THREAD

**Issue by VitaSokolova** [Foso/Ktorfit#549]
### Ktorfit version

1.13.0

### What happened and how can we reproduce this issue?

I noticed that in case of malformed JSON ktorfit crashes my app, even though I wrapped the network call in try/catch. 

Ktor settings (v 2.3.10):
```
fun createHttpClient(
    engine: HttpClientEngine,
    configuration: HttpClientConfiguration,
    headerProvider: HeaderProvider
): HttpClient {
    return HttpClient(engine) {
        // throws an error if the status code is not successful (>=300)
        expectSuccess = true

        // Timeout plugin to set up timeout milliseconds for client
        install(HttpTimeout) {
            socketTimeoutMillis = TIMEOUT_REQUEST_IN_SECONDS * 1000
            requestTimeoutMillis = TIMEOUT_REQUEST_IN_SECONDS * 1000
        }
        // Logging plugin combined with kermit(KMP Logger library)
        install(Logging) {
            level = LogLevel.ALL
            logger = object : Logger {
                override fun log(message: String) {
                    co.touchlab.kermit.Logger.d(tag = "KtorClient", null) {
                        message
                    }
                }
            }
        }
        // We can configure the BASE_URL and also
        // the default headers by defaultRequest builder
        defaultRequest {
            header(HEADER_CONTENT_TYPE, "application/json")
            runBlocking {
                headerProvider.getAuthToken()?.let { token ->
                    header(HEADER_AUTHORIZATION, "Bearer $token")
                }
            }
            url(configuration.getBaseUrl())
        }

        install(ContentNegotiation) {
            json(
                Json {
                    prettyPrint = true
                    isLenient = true
                    ignoreUnknownKeys = true
                    explicitNulls = false
                }
            )
        }

        HttpResponseValidator {
            validateResponse { response ->
                if (!response.status.isSuccess()) {
                    if (response.status == HttpStatusCode.Unauthorized) {
                        configuration.getNetworkErrorHandler().onUnauthorizedError()
                    }
                    throw HttpException(
                        statusCode = response.status.value,
                        body = response.bodyAsText()
                    )
                }
            }
        }
    }
}
```

Ktorfit:
```
        ktorfit {
            httpClient(
                createHttpClient(clientEngine, get(), get())
            )
        }
```

What I expect:
interface FlexpoolApi {

    @GET("/api/v4/data")
    suspend fun getData(): List<FlexpoolDto>
}

What server sends:
```
["WIP (data)"]
```

Crash stacktrace:
```
FATAL EXCEPTION: main
                                                                                                    Process: works.temper.temperAndroid.debug, PID: 30601
                                                                                                    io.ktor.serialization.JsonConvertException: Illegal input: Unexpected JSON token at offset 1: Expected start of the object '{', but had '"' instead at path: $[0]
                                                                                                    JSON input: ["WIP (List of Flexpool Memberships)"]
                                                                                                    	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:90)
                                                                                                    	at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1$2.emit(Emitters.kt:224)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:114)
                                                                                                    	at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1.collect(SafeCollector.common.kt:113)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ReduceKt.firstOrNull(Reduce.kt:239)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source:1)
                                                                                                    	at io.ktor.serialization.ContentConverterKt.deserialize(ContentConverter.kt:123)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation.convertResponse$ktor_client_content_negotiation(ContentNegotiation.kt:232)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:264)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(Unknown Source:13)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(Unknown Source:6)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:131)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:89)
                                                                                                    	at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:177)
                                                                                                    	at io.ktor.client.HttpClient$4.invoke(Unknown Source:11)
                                                                                                    	at io.ktor.client.HttpClient$4.invoke(Unknown Source:6)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:131)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:89)
                                                                                                    	at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invokeSuspend(Logging.kt:201)
                                                                                                    	at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invoke(Unknown Source:11)
                                                                                                    	at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invoke(Unknown Source:6)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:131)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:89)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:99)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:142)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(Unknown Source:13)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(Unknown Source:6)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:131)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:89)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:109)
                                                                                                    	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
                                                                                                    	at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:89)
                                                                                                    	at io.ktor.client.call.HttpClientCall.body(HttpClientCall.kt:115)
                                                                                                    	at de.jensklingenberg.ktorfit.converter.builtin.DefaultSuspendResponseConverterFactory$DefaultSuspendResponseConverter.convert(DefaultSuspendResponseConverterFactory.kt:28)
                                                                                                    	at de.jensklingenberg.ktorfit.internal.KtorfitConverterHelper.suspendRequest(KtorfitConverterHelper.kt:113)
                                                                                                    	at de.jensklingenberg.ktorfit.internal.KtorfitConverterHelper$suspendRequest$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
2024-05-14 13:49:54.741 30601-30601 AndroidRuntime          works.temper.temperAndroid.debug     E  	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@57f449e, Dispatchers.Main.immediate]
                                                                                                    Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1: Expected start of the object '{', but had '"' instead at path: $[0]
                                                                                                    JSON input: ["WIP (List of Flexpool Memberships)"]
                                                                                                    	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
                                                                                                    	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
                                                                                                    	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
                                                                                                    	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:596)
                                                                                                    	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:233)
                                                                                                    	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json$default(AbstractJsonLexer.kt:228)
                                                                                                    	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:225)
                                                                                                    	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:74)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:102)
                                                                                                    	at com.temper.works.flexpool.data.entities.FlexpoolDto$$serializer.deserialize(FlexpoolDto.kt:7)
                                                                                                    	at com.temper.works.flexpool.data.entities.FlexpoolDto$$serializer.deserialize(FlexpoolDto.kt:7)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
                                                                                                    	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
                                                                                                    	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
                                                                                                    	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
                                                                                                    	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
                                                                                                    	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
                                                                                                    	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:82)
```

### What did you expect to happen?

When I handle the error in the code:
```
    private fun loadData() {
        viewModelScope.launch {
            try {
                getDataCall()
            } catch (exception: Exception) {
                val errorType = when {
                    exception is ConnectionException -> ErrorType.NO_INTERNET
                    else -> ErrorType.GENERIC

                }
            }
        }
    }
```

I see catch block working, but the app crashes anyway

**Comment by VitaSokolova** [comment]
Sorry, it's not Ktorfit related, it works with `CoroutineExceptionHandler`, I don't know how to explain this:
```
        val coroutineExceptionHandler = CoroutineExceptionHandler { _, exception ->
            ...
        }
        viewModelScope.launch(coroutineExceptionHandler) {...}
```

**Comment by naixx** [comment]
It's ktorfit issue. If you throw ResponseException there won't be crashes. I had this issue with error validation

**Comment by naixx** [comment]
@Foso I'm using 2.0.0
