### ISSUE TITLE
kotlin 2, ksp 1 and ktorfit clashing in multimodule project

### ISSUE THREAD

**Issue by lepicekmichal** [Foso/Ktorfit#634]
### Ktorfit version

2.0.1

### What happened and how can we reproduce this issue?

Upgrading from kotlin 1.9.24 to kotlin 2.0.x and ktorfit 2.0.1 in my multimodule project has been giving error messages while trying to compile.

I have ktorfit interface inside module A, which sees on module B where class TeamResponse is located.

```kotlin
package com.example.abc.team

import com.example.abc.api.team.TeamResponse
import com.example.abc.api.team.TeamRequest

interface NamedTeamService {

    @GET("named-players-teams")
    suspend fun fetchTeams(): List<TeamResponse>

    @POST("named-players-teams")
    @Headers("Content-Type: application/json")
    suspend fun addTeam(
        @Body team: TeamRequest,
    ): TeamResponse

    @DELETE("named-players-teams/{id}")
    suspend fun deleteTeam(@Path("id") teamId: Int)
}
```

And it will always give this error:
```
[ksp] java.lang.IllegalArgumentException: Error type '<ERROR TYPE: TeamResponse>' is not resolvable in the current round of processing.
	at com.squareup.kotlinpoet.ksp.KsTypesKt.requireNotErrorType(KsTypes.kt:40)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:71)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:202)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:177)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:74)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:65)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName$default(KsTypes.kt:63)
	at de.jensklingenberg.ktorfit.poetspec.UtilsKt.findTypeName(Utils.kt:22)
	at de.jensklingenberg.ktorfit.poetspec.FunctionSpecKt.toFunSpec(FunctionSpec.kt:20)
	at de.jensklingenberg.ktorfit.poetspec.FileSpecKt.getImplClassSpec(FileSpec.kt:101)
	at de.jensklingenberg.ktorfit.generator.ClassGeneratorKt.generateImplClass(ClassGenerator.kt:24)
	at de.jensklingenberg.ktorfit.KtorfitProcessor.process(KtorfitProcessor.kt:50)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:310)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:308)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:308)
	at org.jetbrains.kotlin.analyzer.common.CommonResolverForModuleFactory$Companion.analyzeFiles(CommonResolverForModuleFactory.kt:204)
	at org.jetbrains.kotlin.analyzer.common.CommonResolverForModuleFactory$Companion.analyzeFiles$default(CommonResolverForModuleFactory.kt:143)
	at org.jetbrains.kotlin.cli.metadata.CommonAnalysisKt.runCommonAnalysisIteration$lambda$1(CommonAnalysis.kt:72)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.metadata.CommonAnalysisKt.runCommonAnalysisIteration(CommonAnalysis.kt:71)
	at org.jetbrains.kotlin.cli.metadata.CommonAnalysisKt.runCommonAnalysisForSerialization(CommonAnalysis.kt:38)
	at org.jetbrains.kotlin.cli.metadata.K2MetadataKlibSerializer.analyze(K2MetadataKlibSerializer.kt:45)
	at org.jetbrains.kotlin.cli.metadata.K2MetadataKlibSerializer.analyze(K2MetadataKlibSerializer.kt:40)
	at org.jetbrains.kotlin.cli.metadata.AbstractMetadataSerializer.analyzeAndSerialize(AbstractMetadataSerializer.kt:34)
	at org.jetbrains.kotlin.cli.metadata.K2MetadataCompiler.doExecute(K2MetadataCompiler.kt:134)
	at org.jetbrains.kotlin.cli.metadata.K2MetadataCompiler.doExecute(K2MetadataCompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1556)
	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

If I comment out the TeamResponse, TeamRequest will be the next error. 
If I turn on ksp2, then the nullability issue of ksp2 is first to be served.

### What did you expect to happen?

no error

**Comment by lepicekmichal** [comment]
I arrived to the same problem with your example multiplatform project. All that was needed is create basic module with the Person data class and connect a dependency to the module from shared module.
Same exception.

**Comment by Foso** [comment]
Hi, I just updated the example project to multi module and i don't have any issues https://github.com/Foso/Ktorfit/tree/master/example/MultiplatformExample

**Comment by lepicekmichal** [comment]
This is fascinating problem. If I take your example project, I can build it. However, if I remove all lines regarding ios in build.grade.kts, I will arrive to the bug.
jvm+android is not enough.
If I add any of the ios (x64, macos, doesnt matter), build is working again.

**Comment by lepicekmichal** [comment]
js target is also making it work. I honestly guess it is a KSP problem but maybe you could find out exactly what and work your way around it?

**Comment by Foso** [comment]
okay, thank you for trying it. Maybe i find a solution
