### ISSUE TITLE
[Bug]: kotlinx.coroutines.JobCancellationException: Parent job is Completed

### ISSUE THREAD

**Issue by Syer10** [Foso/Ktorfit#70]
### Ktorfit version

1.0.0-beta14

### What happened and how can we reproduce this issue?

In my application I need to get images, my codebase has a cache that I store the images in.
1. Get a large response, such as image, in my application I get a Flow<HttpResponse>
2. Use HttpResponse.bodyAsChannel(), in my application I pipe it all directly to a cache so there isn't a large amount of memory taken.
3. It eventually throws an exception, here is a small portion of the body

```kotlin
kotlinx.coroutines.JobCancellationException: Parent job is Completed
	at kotlinx.coroutines.JobSupport.getChildJobCancellationCause(JobSupport.kt:714) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.JobSupport.createCauseException(JobSupport.kt:720) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:752) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1462) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.JobSupport.invokeOnCompletion(JobSupport.kt:1549) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.Job$DefaultImpls.invokeOnCompletion$default(Job.kt:341) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.JobSupport.attachChild(JobSupport.kt:970) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.JobSupport.initParentJob(JobSupport.kt:150) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.<init>(AbstractCoroutine.kt:51) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.StandaloneCoroutine.<init>(Builders.common.kt:194) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
```

### What did you expect to happen?

The image would be piped into the cache and it wouldnt error.

### Is there anything else we need to know about?

Maybe use the current coroutine job instead of making a new one for each request? Not sure how it has its own though, couldnt find the code that causes it.

**Comment by Syer10** [comment]
Huh, and then I fix it 5 mins later. Basically the issue is that the FlowResponseConverter(and probably other converters) call `response.body(info)` when the return type is a HttpResponse, which makes another HttpResponse that for some reason errors when trying to get the real body. I fixed it by changing

```kotlin
    override fun <RequestType> convertRequest(
        typeData: TypeData,
        requestFunction: suspend () -> Pair<TypeInfo, HttpResponse?>,
        ktorfit: Ktorfit
    ): Any {
        return flow {
            try {
                val (info, response) = requestFunction()
                emit(response!!.body(info))
            } catch (exception: Exception) {
                throw exception
            }
        }
    }
```
to
```kotlin
    override fun <RequestType> convertRequest(
        typeData: TypeData,
        requestFunction: suspend () -> Pair<TypeInfo, HttpResponse?>,
        ktorfit: Ktorfit
    ): Any {
        return flow {
            try {
                val (info, response) = requestFunction()
                if (info.type == HttpResponse::class) {
                    emit(response!!)
                } else {
                    emit(response!!.body(info))
                }
            } catch (exception: Exception) {
                throw exception
            }
        }
    }
```

**Comment by Foso** [comment]
Thank you for reporting, i fixed in beta15

**Comment by Syer10** [comment]
@Foso This is happening again in the latest releases
